services:
  - type: web
    name: social-media-automation-frontend
    env: static
    rootDir: Frontend
    buildCommand: chmod +x build-debug.sh && ./build-debug.sh
    staticPublishPath: build
    envVars:
      - key: NODE_ENV
        value: production
      - key: GENERATE_SOURCEMAP
        value: false
      - key: CI
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html